### PR TITLE
close #37 Ctrl+Alt+Shift+E to Explorer View from anywhere

### LINKED ISSUE #37: one shortcut Ctrl+Alt+Shift+E should open Explorer View from anywhere
In a way eExplorer is competing with StartExplorer to open Explorer.

With StartExplorer Ctrl+Alt+E can be used to quickly open Explorer.
eExplorer should also give quick shortcut like <kbd>Ctrl+Alt+Shift+E</kbd>

### PR DESCRIPTION
**Pull request by paulvi**
close #37 Ctrl+Alt+Shift+E to Explorer View from anywhere
also from Show in> menu (Alt+Shift+W)

### CODE REVIEW

**Comment by paulvi** [comment]
Please use https://github.com/culmat/eExplorer/pull/42/files?w=0 link to see actual changes

**Comment by paulvi** [comment]
compare with https://github.com/eclipse/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.ide/plugin.xml

search `org.eclipse.ui.ide.showInSystemExplorer`

**Comment by culmat** [comment]
thanks for your contribution Paul. You can now update from eclipse marketplace.

**Comment by paulvi** [comment]
Thank you.

Could you help how to set up continuous delivery ?

**Comment by culmat** [comment]
Here are the main steps in short
* Log into https://travis-ci.org with your github account and sync you project
* Generate a [github oauth token](https://help.github.com/articles/creating-an-access-token-for-command-line-use/) and add as environment variable in your travis project
screen shot 2015-09-21 at 20 32 17
* add .travis.yml like [this one](https://github.com/culmat/eExplorer/blob/master/.travis.yml)
* in the pom.xml of your update site [configure the site-maven-plugin with the oauth token](https://github.com/culmat/eExplorer/blob/master/com.github.culmat.eexplorer.site/pom.xml#L27)

**Pull request merged**
